---
openapi: 3.0.3
info:
  title: Component API
  description: Each ML/AI component, to be integrated in the "logic" of DAG/Controller, should implement these APIs (These APIs and number of input/output parameters could be modified as for devepoler necessity)
  contact: {}
  version: 0.0.1
servers:
- url: http://localhost:8080
tags:
- name: component
  description: Component
paths:
  "/api/status":
    get:
      tags:
      - component
      summary: To get "status" of the long-term execution in the AI/ML component.
      operationId: getStatusUsingGET
      parameters:
      - name: executionid
        in: query
        description: The unique execution uuid.
        required: true
        style: form
        schema:
          type: string
      responses:
        '200':
          description: OK
          content:
            "*/*":
              schema:
                "$ref": "#/components/schemas/ExecutionResultDTO"
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found
  "/api/job":
    post:
      tags:
      - component
      summary:  To post a long-term execution in the AI/ML component.
      operationId: postJobUsingPOST
      requestBody:
        content:
          application/json:
            schema:
              "$ref": "#/components/schemas/ExecutionDTO"
      responses:
        '200':
          description: OK
          content:
            "*/*":
              schema:
                "$ref": "#/components/schemas/ExecutionResultDTO"
        '201':
          description: Created
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found
  "/api/result/{executionid}":
    get:
      tags:
      - component
      summary:  To get the "location" of result in the AI/ML component after long-term execution has been succesfully completed.
      operationId: userByIdUsingGET
      parameters:
      - name: executionid
        in: path
        description: The unique execution uuid.
        required: true
        style: simple
        schema:
          type: string
      responses:
        '200':
          description: OK
          content:
            "*/*":
              schema:
                "$ref": "#/components/schemas/ExecutionResultDTO"
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found
components:
  schemas:
    ExecutionDTO:
      title: ExecutionDTO
      required:
      - executionid
      type: object
      properties:
        executionid:
          type: string
        parameters:
          type: string
      description: Execution DTO
    ExecutionResultDTO:
      title: ExecutionResultDTO
      required:
      - executionid
      - result
      type: object
      properties:
        executionid:
          type: string
        message:
          type: string
        resultlocation:
          type: string
        result:
          type: string
          enum:
          - OK
          - KO
          - PENDING

      description: Execution Result DTO
